# Generated by Django 2.2.7 on 2019-11-12 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complain', models.TextField()),
                ('student', models.CharField(max_length=200)),
                ('complaint_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaint.ComplaintCategory')),
            ],
        ),
    ]
